// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/kv.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyValueStorage_Get_FullMethodName = "/kv.KeyValueStorage/Get"
	KeyValueStorage_Set_FullMethodName = "/kv.KeyValueStorage/Set"
)

// KeyValueStorageClient is the client API for KeyValueStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValueStorageClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Status, error)
}

type keyValueStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueStorageClient(cc grpc.ClientConnInterface) KeyValueStorageClient {
	return &keyValueStorageClient{cc}
}

func (c *keyValueStorageClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Value)
	err := c.cc.Invoke(ctx, KeyValueStorage_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStorageClient) Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, KeyValueStorage_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueStorageServer is the server API for KeyValueStorage service.
// All implementations must embed UnimplementedKeyValueStorageServer
// for forward compatibility.
type KeyValueStorageServer interface {
	Get(context.Context, *Key) (*Value, error)
	Set(context.Context, *KeyValue) (*Status, error)
	mustEmbedUnimplementedKeyValueStorageServer()
}

// UnimplementedKeyValueStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyValueStorageServer struct{}

func (UnimplementedKeyValueStorageServer) Get(context.Context, *Key) (*Value, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKeyValueStorageServer) Set(context.Context, *KeyValue) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedKeyValueStorageServer) mustEmbedUnimplementedKeyValueStorageServer() {}
func (UnimplementedKeyValueStorageServer) testEmbeddedByValue()                         {}

// UnsafeKeyValueStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValueStorageServer will
// result in compilation errors.
type UnsafeKeyValueStorageServer interface {
	mustEmbedUnimplementedKeyValueStorageServer()
}

func RegisterKeyValueStorageServer(s grpc.ServiceRegistrar, srv KeyValueStorageServer) {
	// If the following call panics, it indicates UnimplementedKeyValueStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyValueStorage_ServiceDesc, srv)
}

func _KeyValueStorage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStorage_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStorage_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStorageServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueStorage_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStorageServer).Set(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyValueStorage_ServiceDesc is the grpc.ServiceDesc for KeyValueStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyValueStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv.KeyValueStorage",
	HandlerType: (*KeyValueStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KeyValueStorage_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KeyValueStorage_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kv.proto",
}
